# Generated by Django 5.2.16 on 2026-07-14 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_generatedreport_attempts_generatedreport_finished_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReportTemplateVersion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.PositiveIntegerField()),
                ("template_file", models.CharField(max_length=255)),
                ("fields_schema", models.JSONField(blank=True, default=list)),
                ("checksum", models.CharField(blank=True, default="", max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("validated", "Validated"),
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("rejected", "Rejected"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_template_versions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "report_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="versions", to="reports.reporttype"
                    ),
                ),
            ],
            options={
                "ordering": ["report_type", "-version"],
            },
        ),
        migrations.AddField(
            model_name="generatedreport",
            name="template_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="generated_reports",
                to="reports.reporttemplateversion",
            ),
        ),
        migrations.AddIndex(
            model_name="reporttemplateversion",
            index=models.Index(fields=["report_type", "status"], name="reports_rep_report__29b0f9_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="reporttemplateversion",
            unique_together={("report_type", "version")},
        ),
    ]
