# Generated by Django 5.2.16 on 2026-07-28 09:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_service_restriction_starts_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['action', 'target_type', 'target_id'], name='reports_aud_action_11faf8_idx'),
        ),
    ]
